// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-pTgN88pQD6xjP2zR8_21DGMSL9EQu0I',
    appId: '1:135155850282:web:cb2e53c8ab68c886d93753',
    messagingSenderId: '135155850282',
    projectId: 'ditonton-4d056',
    authDomain: 'ditonton-4d056.firebaseapp.com',
    storageBucket: 'ditonton-4d056.firebasestorage.app',
    measurementId: 'G-WKS7XTTZ7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSjRknQZdoIY82py1p_RaRO7tGq2DBrjg',
    appId: '1:135155850282:android:ba4b49702ed643f8d93753',
    messagingSenderId: '135155850282',
    projectId: 'ditonton-4d056',
    storageBucket: 'ditonton-4d056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Yllbu8dm9xXD7z1FRtpOS_2Ow1Y0cWc',
    appId: '1:135155850282:ios:e9f0ec36eafd0915d93753',
    messagingSenderId: '135155850282',
    projectId: 'ditonton-4d056',
    storageBucket: 'ditonton-4d056.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
